---
title: "lab06_exercises"
author: "Eva Frossard"
format: html
editor: visual
---

# Load libraries

{r}
library(tidyverse)
library(broom)


# Load Data

{r}
raw_dir <- "/home/projects/lab07_git_exercises"
data_file <- "gravier.RData"
data_loc <- "https://github.com/ramhiser/datamicroarray/raw/master/data/"

if( !dir.exists(raw_dir) ){
  dir.create(path = raw_dir)
}
if( !file.exists(str_c(raw_dir, data_file)) ){
  download.file(
    url = str_c(data_loc, data_file),
    destfile = str_c(raw_dir, data_file))
}
load(file = str_c(raw_dir, data_file))


# Tidy the data

{r}
gravier_clean <- gravier |>
  bind_cols() |> # binds the two dataframes by columns
  as_tibble()


write_tsv(gravier_clean, 
       file="/home/projects/lab07_git_exercises/02_gravier_clean.tsv.gz"
       )


{r}
gravier_clean_aug <- gravier_clean |>
  relocate(early_metastasis = y)


# PCA analysis

{r}
pca_fit <- gravier_clean_aug |> 
  select(where(is.numeric)) |> 
  prcomp(scale = TRUE)


# Scatter plot

{r}
pca_fit |> 
  augment(gravier_clean_aug) |> 
  ggplot(aes(.fittedPC1, .fittedPC2, color = early_metastasis)) + 
  geom_point(size = 1.5) +
  scale_color_manual(
    values = c(good = "pink", poor = "darkblue")
  ) 



The PC coordinates are combined with the gravier_clean_aug data set. The categorical variable early_metastasis is colored. On the y-axis the fittedPC variable is 2 and on the x-axis the fitted PC variable is 1. The interpretation of the PC variables is complicated when using categorical variables. There is no pattern and no clusters discernible in this scatterplot. Further consideration of the data is necessary. 

# Rotation matrix

{r}
arrow_style <- arrow(
  angle = 20, ends = "first", type = "closed", length = grid::unit(8, "pt")
)

# plot rotation matrix
pca_fit |> 
  tidy(matrix = "rotation") |> 
  pivot_wider(names_from = "PC", names_prefix = "PC", values_from = "value") |> 
  head(10) |> 
  ggplot(aes(PC1, PC2)) +
  geom_segment(xend = 0, yend = 0, arrow = arrow_style) +
  geom_text(
    aes(label = column),
    hjust = 1, nudge_x = +0.01, 
    color = "#904C2F"
  ) +
  xlim(-0.05, 0.06) + ylim(-0.05, 0.05) +
  coord_fixed()

To be able to trace a discernible plot, we chose only 10 genes. The longer the vectors, the more they have an influence on the dataset. Here, g7F07 seem to be the more significant, however without a strong influence. Once again this plot doesn't seem very useful to exploit the data. 


# Variance explained by each PC

{r}
pca_fit |> 
  tidy(matrix = "eigenvalues") |> 
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8) +
  scale_x_continuous(breaks = 1:9) +
  scale_y_continuous(
    labels = scales::percent_format(),
    expand = expansion(mult = c(0, 0.01))
  ) +
  theme(
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  )
  


PC1 explains 8.2% of the data which is may seem low. However, seeing the important number of PC, it still seems quite significant. It is followed upclose by PC2 which seems to explain 7%. 

# Conclusion 

On the contrary to the analysis using Purr performed two weeks ago, we have here an analysis using PC that doesn't seem too conclusive. This doesn't mean that some genes don't have influence on the presence of early metastasis, however it means that this model is not adequate to outline this relationship in particular.
